FROM maven:3.8.3-openjdk-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM maven:3.8.3-openjdk-17

COPY --from=build /app/target/*.jar app.jar
COPY .env /.env

CMD ["java", "-jar", "/app.jar"]
