services:
  pg:
    container_name: etherium-fetcher-postgress
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - POSTGRES_SSL_MODE=allow
    ports:
      - "${PG_PORT}:5432"

