networks:
   limeapi-network:
     external: true

services:
  pg:
    container_name: limeapi-postgress
    image: postgres:alpine
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME:-postgres}"
      - "POSTGRES_USER=${PG_USER:-limechain}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD:-limechain}"
      - POSTGRES_SSL_MODE=allow
    ports:
      - "${PG_PORT:-54322}:5432"
    networks:
      - limeapi-network
    volumes:
      - type: volume
        source: ''
        target: /var/lib/postgresql/data  # Путь внутри контейнера для хранения данных
